# Generated by Django 4.1.7 on 2023-04-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0003_aluno_num_respostas'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='limite_respostas',
            field=models.IntegerField(default=23),
        ),
    ]
